Models/ThamGiaHoatDong.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace website_CLB_HTSV.Models
{
    public class ThamGiaHoatDong
    {
        [Key]
        [StringLength(20)]
        public string? MaThamGiaHoatDong { get; set; }

        [StringLength(20)]
        public string? MaDangKy { get; set; }

        [StringLength(20)]
        public string? MaSV { get; set; }

        [StringLength(20)]
        public string? MaHoatDong { get; set; }

        [DisplayName("Đã Tham Gia")]
        public bool DaThamGia { get; set; }

        [DisplayName("Link Minh Chứng")]
        public string? LinkMinhChung { get; set; } // Thêm thuộc tính mới để chứa link minh chứng

        [ForeignKey("MaDangKy")]
        [DisplayName("Đăng Ký Hoạt Động")]
        public DangKyHoatDong? DangKyHoatDong { get; set; }
    }
}

Controllers/ThamGiaHoatDongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using website_CLB_HTSV.Data;
using website_CLB_HTSV.Models;
using System.Globalization;
namespace website_CLB_HTSV.Controllers
{
    public class ThamGiaHoatDongsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ThamGiaHoatDongsController(ApplicationDbContext context)
        {
            _context = context;
        }
        //Xuât danh sách

        //Cập nhật minh chứng 
        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> XuatDS()
        {
            var activityList = await _context.HoatDong.Where(t => t.TrangThai == "Đã kết thúc")
                                             .Select(a => new SelectListItem
                                             {
                                                 Value = a.MaHoatDong.ToString(),
                                                 Text = a.TenHoatDong
                                             })
                                             .ToListAsync();

            ViewBag.ActivityList = activityList;

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> XuatDS(string hoatDongId)
        {
            var activityList = await _context.HoatDong
                                             .Select(a => new SelectListItem
                                             {
                                                 Value = a.MaHoatDong.ToString(),
                                                 Text = a.TenHoatDong
                                             })
                                             .ToListAsync();

            ViewBag.ActivityList = activityList;

            // Lấy danh sách sinh viên tham gia hoạt động được chọn
            var danhSachSinhVien = from s in _context.ThamGiaHoatDong
                                   .Where(tg => tg.MaHoatDong == hoatDongId && tg.DaThamGia == true)
                                   .Include(t => t.DangKyHoatDong)
                                   .Include(h => h.DangKyHoatDong.HoatDong)
                                   .Include(s => s.DangKyHoatDong.SinhVien)
                                   select s;

            // Tạo một package Excel mới
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial; // Khai báo loại giấy phép
            using (var package = new ExcelPackage())
            {
                // Tạo một Sheet mới
                var worksheet = package.Workbook.Worksheets.Add("Danh sách sinh viên");

                // Đặt các tiêu đề cho các cột
                worksheet.Cells[1, 1].Value = "STT";
                worksheet.Cells[1, 2].Value = "MSSV";
                worksheet.Cells[1, 3].Value = "Họ và tên";
                worksheet.Cells[1, 4].Value = "Mã lớp";

                // Có thể thêm các tiêu đề khác tùy ý

                // Đặt dữ liệu cho từng hàng
                int row = 2;
                int i = 1;
                foreach (var sinhVien in danhSachSinhVien)
                {
                    worksheet.Cells[row, 1].Value = i;
                    worksheet.Cells[row, 2].Value = sinhVien.MaSV;
                    worksheet.Cells[row, 3].Value = sinhVien.DangKyHoatDong.SinhVien.HoTen;
                    worksheet.Cells[row, 4].Value = sinhVien.DangKyHoatDong.SinhVien.MaLop;

                    // Có thể thêm dữ liệu cho các cột khác tùy ý
                    row++;
                    i++;
                }
                var hoatDong = await _context.HoatDong.FindAsync(hoatDongId);
                string tenhd = hoatDong.TenHoatDong.ToString();
                TextInfo textInfo = new CultureInfo("vi-VN", false).TextInfo;
                string titleCase = textInfo.ToTitleCase(tenhd);
                string tgian = hoatDong.ThoiGian.ToString("dd-MM-yyyy");
                // Lưu trữ tệp Excel vào một MemoryStream
                var stream = new MemoryStream(package.GetAsByteArray());
                string fileName = $"DS_HoatDong_Ngay: {tgian}_{titleCase}.xlsx";
                // Trả về phản hồi file Excel
                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
            }
        }




        // GET: ThamGiaHoatDongs
        public async Task<IActionResult> Index(string searchString, int? pageNumber)
        {
            IQueryable<ThamGiaHoatDong> danhSachThamGiaHoatDong = _context.ThamGiaHoatDong
                .Include(t => t.DangKyHoatDong)
                .Include(h => h.DangKyHoatDong.HoatDong)
                .Include(s => s.DangKyHoatDong.SinhVien);

            // Lọc theo chuỗi tìm kiếm nếu có
            if (!string.IsNullOrEmpty(searchString))
            {
                danhSachThamGiaHoatDong = danhSachThamGiaHoatDong.Where(tg => tg.DangKyHoatDong.HoatDong.MaHoatDong.Contains(searchString) || tg.DangKyHoatDong.HoatDong.TenHoatDong.Contains(searchString) || tg.MaSV.Contains(searchString));
            }

            // Kiểm tra người dùng đã đăng nhập hay chưa
            if (!User.Identity.IsAuthenticated)
            {
                // Nếu chưa đăng nhập, đặt thông báo vào TempData
                TempData["ErrorMessage"] = "Bạn cần đăng nhập để truy cập vào trang này.";
                return Redirect("/Identity/Account/Login");
            }
            else
            {
                // Lấy trang hiện tại, mặc định là trang đầu tiên nếu không được xác định
                pageNumber ??= 1;

                // Kiểm tra vai trò của người dùng
                if (User.IsInRole("Administrators"))
                {
                    // Nếu là quản trị viên, trả về view với toàn bộ danh sách phân trang
                    var paginatedDanhSachThamGiaHoatDong = await PaginatedList<ThamGiaHoatDong>.CreateAsync(danhSachThamGiaHoatDong.AsNoTracking(), pageNumber.Value, 10); // 10 là kích thước trang
                    return View(paginatedDanhSachThamGiaHoatDong);
                }
                else
                {
                    // Nếu không phải là quản trị viên, lọc theo mã số sinh viên và trả về view với danh sách phân trang
                    var mssv = User.Identity.Name.Split('@')[0];
                    danhSachThamGiaHoatDong = danhSachThamGiaHoatDong.Where(h => h.MaSV == mssv);
                    var paginatedDanhSachThamGiaHoatDong = await PaginatedList<ThamGiaHoatDong>.CreateAsync(danhSachThamGiaHoatDong.AsNoTracking(), pageNumber.Value, 10); // 10 là kích thước trang
                    return View(paginatedDanhSachThamGiaHoatDong);
                }
            }
        }








        // GET: ThamGiaHoatDongs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.ThamGiaHoatDong == null)
            {
                return NotFound();
            }

            var thamGiaHoatDong = await _context.ThamGiaHoatDong
                .Include(t => t.DangKyHoatDong)
                .FirstOrDefaultAsync(m => m.MaThamGiaHoatDong == id);
            if (thamGiaHoatDong == null)
            {
                return NotFound();
            }

            return View(thamGiaHoatDong);
        }

        // GET: ThamGiaHoatDongs/Create
        [Authorize(Roles = "Administrators")]
        public IActionResult Create()
        {
            ViewData["MaDangKy"] = new SelectList(_context.DangKyHoatDong, "MaDangKy", "MaDangKy");
            return View();
        }

        // POST: ThamGiaHoatDongs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> Create([Bind("MaThamGiaHoatDong,MaDangKy,MaSV,MaHoatDong,DaThamGia,LinkMinhChung")] ThamGiaHoatDong thamGiaHoatDong)
        {
            if (ModelState.IsValid)
            {
                _context.Add(thamGiaHoatDong);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDangKy"] = new SelectList(_context.DangKyHoatDong, "MaDangKy", "MaDangKy", thamGiaHoatDong.MaDangKy);
            return View(thamGiaHoatDong);
        }

        // GET: ThamGiaHoatDongs/Edit/5
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.ThamGiaHoatDong == null)
            {
                return NotFound();
            }

            var thamGiaHoatDong = await _context.ThamGiaHoatDong.FindAsync(id);
            if (thamGiaHoatDong == null)
            {
                return NotFound();
            }
            ViewData["MaDangKy"] = new SelectList(_context.DangKyHoatDong, "MaDangKy", "MaDangKy", thamGiaHoatDong.MaDangKy);
            return View(thamGiaHoatDong);
        }

        // POST: ThamGiaHoatDongs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> Edit(string id, [Bind("MaThamGiaHoatDong,MaDangKy,MaSV,MaHoatDong,DaThamGia,LinkMinhChung")] ThamGiaHoatDong thamGiaHoatDong)
        {
            if (id != thamGiaHoatDong.MaThamGiaHoatDong)
            {
                return NotFound();
            }

            if (ModelState.IsValid)

Views/ThamGiaHoatDongs/Create.cshtml
@model website_CLB_HTSV.Models.ThamGiaHoatDong

@{
    if (User.IsInRole("Administrators"))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
}

<h1>Create</h1>

<h4>ThamGiaHoatDong</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaThamGiaHoatDong" class="control-label"></label>
                <input asp-for="MaThamGiaHoatDong" class="form-control" />
                <span asp-validation-for="MaThamGiaHoatDong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaDangKy" class="control-label"></label>
                <select asp-for="MaDangKy" class ="form-control" asp-items="ViewBag.MaDangKy"></select>
            </div>
            <div class="form-group">
                <label asp-for="MaSV" class="control-label"></label>
                <input asp-for="MaSV" class="form-control" />
                <span asp-validation-for="MaSV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaHoatDong" class="control-label"></label>
                <input asp-for="MaHoatDong" class="form-control" />
                <span asp-validation-for="MaHoatDong" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="DaThamGia" /> @Html.DisplayNameFor(model => model.DaThamGia)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="LinkMinhChung" class="control-label"></label>
                <input asp-for="LinkMinhChung" class="form-control" />
                <span asp-validation-for="LinkMinhChung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/ThamGiaHoatDongs/Delete.cshtml
@model website_CLB_HTSV.Models.ThamGiaHoatDong

@{
    if (User.IsInRole("Administrators"))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ThamGiaHoatDong</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaSV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaSV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaHoatDong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaHoatDong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DaThamGia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DaThamGia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkMinhChung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkMinhChung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DangKyHoatDong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DangKyHoatDong.MaDangKy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaThamGiaHoatDong" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/ThamGiaHoatDongs/Details.cshtml
@model website_CLB_HTSV.Models.ThamGiaHoatDong

@{
    if (User.IsInRole("Administrators"))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
}

<h1>Details</h1>

<div>
    <h4>ThamGiaHoatDong</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaSV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaSV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaHoatDong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaHoatDong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DaThamGia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DaThamGia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkMinhChung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkMinhChung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DangKyHoatDong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DangKyHoatDong.MaDangKy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaThamGiaHoatDong">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/ThamGiaHoatDongs/Index.cshtml
@model PaginatedList<ThamGiaHoatDong>

@{
    if (User.IsInRole("Administrators"))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
}

@if (User.IsInRole("Administrators"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
    <form asp-controller="ThamGiaHoatDongs" asp-action="Index" class="search-form justify-center mb-2">
        <div class="search-container">
            <input type="text" class="search-input w-full md:w-80 mb-2 md:mb-0" placeholder="Tìm kiếm" name="searchString">
            <button  class="search-button ml-2">
                <i class="bi bi-search"></i>
            </button>
        </div>
    </form>
<h2 class="text-2xl font-semibold mb-4 overflow-y-auto" style="max-height: calc(3 * (3.5rem + 1rem));">Hoạt động đã tham gia</h2>

@{
    int count = (10 * (Model.PageIndex - 1)) + 1;   
}

<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

<div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-black uppercase bg-gray-50 dark:bg-gray-700 ">
            <tr>
                <th scope="col" class="px-6 py-3">
                    STT
                </th>
                <th scope="col" class="px-6 py-3">
                    Tham Gia
                </th>
            @if (User.IsInRole("Administrators"))
            {

                <th scope="col" class="px-6 py-3">
                    MSSV
                </th>
                <th scope="col" class="px-6 py-3">
                    Họ tên
                </th>
            }
                <th scope="col" class="px-6 py-3">
                    Hoạt động
                </th>
                <th scope="col" class="px-6 py-3">
                    Ngày
                </th>
                <th scope="col" class="px-6 py-3">
                    Link minh chứng
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var i in Model.Items)
            {
                <tr class="bg-white border-2 dark:bg-gray-800 dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 whitespace-nowrap">
                        @count
                    </th>
                    @if (i.DaThamGia == true)
                    {
                        <th class="text-green-600 px-6 py-4 whitespace-nowrap">
                            Đã tham gia
                        </th>
                    }
                    else
                    {
                        <th class="text-red-600 px-6 py-4 whitespace-nowrap">
                            Vắng
                        </th>
                    }

                    @if (User.IsInRole("Administrators"))
                    {
                    <td class="px-6 py-4 whitespace-nowrap">
                            @i.MaSV
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                            @i.DangKyHoatDong.SinhVien.HoTen
                    </td>
                    }
                    <td class="px-6 py-4 whitespace-nowrap">
                            @i.DangKyHoatDong.HoatDong.TenHoatDong
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                        @i.DangKyHoatDong.HoatDong.ThoiGian.ToString("dd/MM/yyyy")
                    </td>
                        @if (i.LinkMinhChung != null)
                        {
                        <td class ="px-6 whitespace-nowrap">
                            @{
                                string[] parts = i.LinkMinhChung.Split('/');

                                // Lấy phần thứ 4 của mảng (sau khi chia bởi "/")
                                string id = parts[5];
                                string l = "https://drive.google.com/uc?id=" +  $"{id}" + "&export=download";
                            }
                            <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />

                            <div class="flex items-start my-2.5 bg-gray-50 dark:bg-gray-600 rounded-xl">
                                <div class="me-2">
                                    <span class="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-white pb-2">
                                        <svg fill="none" aria-hidden="true" class="w-5 h-5 flex-shrink-0" viewBox="0 0 20 21">
                                            <g clip-path="url(#clip0_3173_1381)">
                                                <path fill="#E2E5E7" d="M5.024.5c-.688 0-1.25.563-1.25 1.25v17.5c0 .688.562 1.25 1.25 1.25h12.5c.687 0 1.25-.563 1.25-1.25V5.5l-5-5h-8.75z" />
                                                <path fill="#B0B7BD" d="M15.024 5.5h3.75l-5-5v3.75c0 .688.562 1.25 1.25 1.25z" />
                                                <path fill="#CAD1D8" d="M18.774 9.25l-3.75-3.75h3.75v3.75z" />
                                                <path fill="#F15642" d="M16.274 16.75a.627.627 0 01-.625.625H1.899a.627.627 0 01-.625-.625V10.5c0-.344.281-.625.625-.625h13.75c.344 0 .625.281.625.625v6.25z" />
                                                <path fill="#fff" d="M3.998 12.342c0-.165.13-.345.34-.345h1.154c.65 0 1.235.435 1.235 1.269 0 .79-.585 1.23-1.235 1.23h-.834v.66c0 .22-.14.344-.32.344a.337.337 0 01-.34-.344v-2.814zm.66.284v1.245h.834c.335 0 .6-.295.6-.605 0-.35-.265-.64-.6-.64h-.834zM7.706 15.5c-.165 0-.345-.09-.345-.31v-2.838c0-.18.18-.31.345-.31H8.85c2.284 0 2.234 3.458.045 3.458h-1.19zm.315-2.848v2.239h.83c1.349 0 1.409-2.24 0-2.24h-.83zM11.894 13.486h1.274c.18 0 .36.18.36.355 0 .165-.18.3-.36.3h-1.274v1.049c0 .175-.124.31-.3.31-.22 0-.354-.135-.354-.31v-2.839c0-.18.135-.31.355-.31h1.754c.22 0 .35.13.35.31 0 .16-.13.34-.35.34h-1.455v.795z" />
                                                <path fill="#CAD1D8" d="M15.649 17.375H3.774V18h11.875a.627.627 0 00.625-.625v-.625a.627.627 0 01-.625.625z" />
                                            </g>
                                            <defs>
                                                <clipPath id="clip0_3173_1381">
                                                    <path fill="#fff" d="M0 0h20v20H0z" transform="translate(0 .5)" />
                                                </clipPath>
                                            </defs>
                                        </svg>
                                        File minh chứng
                                    </span>
                                    <span class="flex text-xs font-normal text-gray-500 dark:text-gray-400 gap-2">
                                        Google Drive
                                        <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" class="self-center" width="3" height="4" viewBox="0 0 3 4" fill="none">
                                            <circle cx="1.5" cy="2" r="1.5" fill="#6B7280" />
                                        </svg>

                                        PDF
                                    </span>
                                </div>
                                <div class="inline-flex self-center items-center">
                                    <a href="@l" class="inline-flex self-center items-center p-2 text-sm font-medium text-center text-gray-900 bg-gray-50 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-600 dark:hover:bg-gray-500 dark:focus:ring-gray-600" type="button">
                                        <svg class="w-4 h-4 text-gray-900 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                            <path d="M14.707 7.793a1 1 0 0 0-1.414 0L11 10.086V1.5a1 1 0 0 0-2 0v8.586L6.707 7.793a1 1 0 1 0-1.414 1.414l4 4a1 1 0 0 0 1.416 0l4-4a1 1 0 0 0-.002-1.414Z" />
                                            <path d="M18 12h-2.55l-2.975 2.975a3.5 3.5 0 0 1-4.95 0L4.55 12H2a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2Zm-3 5a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z" />
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </td>
                        }
                        else
                        {
                        <td class ="px-6 py-4 whitespace-nowrap">
                            Đang cập nhật
                        </td>
                        }
                        @if (User.IsInRole("Administrators"))
                        {
                        <td class="px-6 py-4 whitespace-nowrap">
                            <a asp-action="Edit" asp-route-id="@i.MaThamGiaHoatDong">Edit</a> |
                            <a asp-action="Details" asp-route-id="@i.MaThamGiaHoatDong">Details</a> |
                            <a asp-action="Delete" asp-route-id="@i.MaThamGiaHoatDong">Delete</a>
                        </td>
                        }
                </tr>
                count++;

            }
        </tbody>
    </table>
</div>

<!-- Pagination -->
<nav aria-label="Page navigation" class="mt-3">
    <ul class="pagination">
        <li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
            <a class="page-link" asp-controller="ThamGiaHoatDongs" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex - 1)">Previous</a>
        </li>
        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            <li class="page-item @(i == Model.PageIndex ? "active" : "")">
                <a class="page-link" asp-controller="ThamGiaHoatDongs" asp-action="Index" asp-route-pageNumber="@i">@i</a>
            </li>
        }
        <li class="page-item @(Model.HasNextPage ? "" : "disabled")">
            <a class="page-link" asp-controller="ThamGiaHoatDongs" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)">Next</a>
        </li>
    </ul>
</nav>




<style>

    /* Form */
    .search-form {
        display: flex;
        justify-content: center;
        margin-bottom: 20px;
    }

    .search-container {
        position: relative;
        width: 100%; /* Thanh tìm kiếm sẽ căng toàn bộ chiều rộng của phần tử cha */
    }

    .search-input {
        width: 100%;
        padding: 10px 20px;
        border: 1px solid #38b7fd;
        border-radius: 25px;
        font-size: 16px;
        outline: none;
        background-color: transparent;
    }

    .search-button {
        position: absolute;
        top: 50%;
        right: 10px;
        transform: translateY(-50%);
        background-color: transparent;
        border: none;
        cursor: pointer;
        padding-bottom: 10px;
    }

        .search-button i {
            font-size: 20px;
        }

    @@media (min-width: 640px) {
        .search-container {
            width: 700px;
        }

        .search-input {
            width: 700px; /* Đặt lại kích thước cho trường hợp màn hình lớn hơn 640px */
            min-width: 200px; /* Đặt kích thước tối thiểu cho ô tìm kiếm */
        }
    }

</style>

Views/ThamGiaHoatDongs/XuatDS.cshtml
@model IEnumerable<website_CLB_HTSV.Models.SinhVien>
@{
    if (User.IsInRole("Administrators"))
    {
         Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    ViewData["Title"] = "Xuất danh sách sinh viên tham gia hoạt động";
}

<h1>@ViewData["Title"]</h1>

<form method="post">
    <div class="form-group">
        <label for="hoatDongId">Chọn hoạt động:</label>
        <select class="form-control" id="hoatDongId" name="hoatDongId">
            @foreach (var item in ViewBag.ActivityList)
            {
                <option value="@item.Value">@item.Text</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Xuất Danh Sách</button>
</form>